@HostAddress = http://localhost:5035

### 1.) Invalid data with FluentValidation:

POST {{HostAddress}}/api/products-v1/
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "price": -10
}

### 2.) ForEvolve.FluentValidation:

POST {{HostAddress}}/api/products-v2/
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "price": -10
}

### 3.) SharpGrip.FluentValidation:

POST {{HostAddress}}/api/products-v3/
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "price": -10
}

### 4.) Valid data with FluentValidation:

POST {{HostAddress}}/api/products-V1/
Accept: application/json
Content-Type: application/json

{
  "name": "Product 1",
  "price": 12.35
}

